# Generated by Django 4.2.2 on 2023-06-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_page_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='is_home_page',
        ),
    ]
