# Generated by Django 4.2.2 on 2023-06-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_page_is_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='page',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='page',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Инстаграмм'),
        ),
        migrations.AddField(
            model_name='page',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Мобильный'),
        ),
        migrations.AddField(
            model_name='page',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='page',
            name='vk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вконтакте'),
        ),
    ]
