# Generated by Django 4.2.2 on 2023-06-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_page_address_page_email_page_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_home_page',
            field=models.BooleanField(default=False, verbose_name='Назначить главной страницей'),
        ),
    ]
