# Generated by Django 4.2.2 on 2023-06-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_html_page_html_block_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='html_block_technology',
            field=models.TextField(blank=True, null=True, verbose_name='Html технологии'),
        ),
    ]
