# Generated by Django 4.2.2 on 2023-07-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_page_html_block_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_1',
            field=models.FileField(blank=True, null=True, upload_to='page'),
        ),
        migrations.AddField(
            model_name='page',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to='page'),
        ),
        migrations.AddField(
            model_name='page',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to='page'),
        ),
        migrations.AddField(
            model_name='page',
            name='image_4',
            field=models.FileField(blank=True, null=True, upload_to='page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='preview_image',
            field=models.FileField(blank=True, null=True, upload_to='page'),
        ),
    ]
