# Generated by Django 4.2.2 on 2023-07-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_page_image_1_page_image_2_page_image_3_page_image_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок первый'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок второй'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок третий'),
        ),
    ]
