# Generated by Django 4.2.2 on 2023-07-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_page_title_1_page_title_2_page_title_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image_4',
        ),
    ]
