# Generated by Django 4.2.2 on 2023-07-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_page_image_1_remove_page_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='faq_1_answer',
            field=models.TextField(blank=True, verbose_name='Ответ 1'),
        ),
        migrations.AddField(
            model_name='page',
            name='faq_1_question',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вопрос 1'),
        ),
        migrations.AddField(
            model_name='page',
            name='faq_2_answer',
            field=models.TextField(blank=True, verbose_name='Ответ 2'),
        ),
        migrations.AddField(
            model_name='page',
            name='faq_2_question',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вопрос 2'),
        ),
        migrations.AddField(
            model_name='page',
            name='faq_3_answer',
            field=models.TextField(blank=True, verbose_name='Ответ 3'),
        ),
        migrations.AddField(
            model_name='page',
            name='faq_3_question',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вопрос 3'),
        ),
        migrations.AddField(
            model_name='page',
            name='faq_4_answer',
            field=models.TextField(blank=True, verbose_name='Ответ 4'),
        ),
        migrations.AddField(
            model_name='page',
            name='faq_4_question',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вопрос 4'),
        ),
        migrations.AddField(
            model_name='page',
            name='faq_5_answer',
            field=models.TextField(blank=True, verbose_name='Ответ 5'),
        ),
        migrations.AddField(
            model_name='page',
            name='faq_5_question',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вопрос 5'),
        ),
    ]
