# Generated by Django 4.2.2 on 2023-07-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_page_faq_1_answer_page_faq_1_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('web', 'Создание сайтов'), ('mobile', 'Мобильная разработка'), ('marketing', ' Реклама')], default='web', max_length=100, verbose_name='Категория страницы'),
        ),
    ]
