# Generated by Django 4.2.2 on 2023-07-01 13:57

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Дружественный URL')),
                ('meta_description', models.TextField(verbose_name='Мета описание')),
                ('preview_image', models.FileField(upload_to='preview', verbose_name='Превью')),
                ('task', ckeditor.fields.RichTextField(blank=True, verbose_name='Задача')),
                ('solution', ckeditor.fields.RichTextField(blank=True, verbose_name='Решение')),
                ('ca', models.TextField(blank=True, verbose_name='Целевая аудитория')),
                ('image', models.FileField(blank=True, upload_to='case', verbose_name='Изображение 1')),
                ('content_1', ckeditor.fields.RichTextField(blank=True, verbose_name='Блок 1')),
                ('image_2', models.FileField(blank=True, upload_to='case', verbose_name='Изображение 2')),
                ('content_2', ckeditor.fields.RichTextField(blank=True, verbose_name='Блок 2')),
                ('image_3', models.FileField(blank=True, upload_to='case', verbose_name='Изображение 3')),
                ('content_3', ckeditor.fields.RichTextField(blank=True, verbose_name='Блок 3')),
                ('link_to_site', models.CharField(blank=True, max_length=100, verbose_name='Ссылка на сайт')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания')),
                ('client', models.CharField(blank=True, max_length=255, verbose_name='Клиент')),
                ('show_on_home', models.BooleanField(default=0, verbose_name='Показывать на главной')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['-pk'],
            },
        ),
    ]
