# Generated by Django 4.2.2 on 2023-07-01 14:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='content_4',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Блок 3'),
        ),
        migrations.AddField(
            model_name='case',
            name='image_4',
            field=models.FileField(blank=True, upload_to='case', verbose_name='Изображение 3'),
        ),
    ]
