# Generated by Django 4.2.2 on 2023-07-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_content_4_case_image_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='meta_title',
            field=models.TextField(blank=True, verbose_name='Мета заголовок'),
        ),
    ]
