# Generated by Django 4.2.2 on 2023-06-27 19:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Дружественный URL')),
                ('meta_description', models.TextField(verbose_name='Мета описание')),
                ('preview_image', models.FileField(upload_to='preview', verbose_name='Превью')),
                ('image', models.FileField(upload_to='portfolio', verbose_name='Изображение большое')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('link_to_site', models.CharField(blank=True, max_length=100, verbose_name='Ссылка на сайт')),
                ('category', models.CharField(blank=True, choices=[('visitka', 'Многостраничник'), ('shop', 'Интернет-магазин'), ('landing', 'Лэндинг')], default=1, max_length=50, verbose_name='Категория сайта')),
                ('show_on_home', models.BooleanField(default=0, verbose_name='Показывать на главной')),
            ],
            options={
                'verbose_name': 'Работу',
                'verbose_name_plural': 'Портфолио',
                'ordering': ['-pk'],
            },
        ),
    ]
