# Generated by Django 4.2.2 on 2023-06-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image_2',
            field=models.FileField(blank=True, upload_to='portfolio', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='work',
            name='image_3',
            field=models.FileField(blank=True, upload_to='portfolio', verbose_name='Изображение 3'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.FileField(blank=True, upload_to='portfolio', verbose_name='Изображение 1'),
        ),
    ]
