# Generated by Django 4.2.2 on 2023-06-30 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_work_image_2_work_image_3_alter_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 6, 30), verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='work',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 6, 30), verbose_name='Дата начала'),
        ),
    ]
