# Generated by Django 4.2.2 on 2023-06-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_work_end_date_alter_work_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='client',
            field=models.CharField(blank=True, max_length=255, verbose_name='Клиент'),
        ),
    ]
