# Generated by Django 4.2.2 on 2023-07-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_work_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image_4',
            field=models.FileField(blank=True, upload_to='portfolio', verbose_name='Изображение 3'),
        ),
    ]
