# Generated by Django 4.2.2 on 2023-07-01 11:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_work_image_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='content',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image_4',
        ),
        migrations.AddField(
            model_name='work',
            name='solution',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='work',
            name='task',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
    ]
