# Generated by Django 4.2.2 on 2023-07-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_work_content_remove_work_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='technology',
            field=models.TextField(blank=True, verbose_name='Технологии'),
        ),
    ]
