# Generated by Django 4.2.2 on 2023-07-01 13:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_work_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='solution',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='work',
            name='task',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Задача'),
        ),
    ]
