# Generated by Django 4.2.2 on 2023-07-31 10:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_work_solution_alter_work_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='technology',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Технологии'),
        ),
    ]
