# Generated by Django 4.2.2 on 2023-08-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_work_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='meta_title',
            field=models.TextField(blank=True, verbose_name='Мета заголовок'),
        ),
    ]
